### ISSUE TITLE
Practice

### ISSUE THREAD

**Issue by MrTrvp** [UbbeLoL/uRAT#3]
Why do you compare against an empty string instead of using inbuilt methods such as "IsNullOrWhitespace"?

https://github.com/UbbeLoL/uRAT/blob/master/uRAT.Server/Forms/BuildClientForm.cs#L89
https://github.com/UbbeLoL/uRAT/blob/master/uRAT.Server/Forms/BuildClientForm.cs#L106

**Comment by UbbeLoL** [comment]
No reason, feel free to make a pull request if you wanna fix it.
